"use client";

import { useState } from "react";
import Link from "next/link";
import { formatDateTime } from "@/lib/utils";
import { 
  Sparkles, 
  Bot, 
  CalendarDays, 
  TrendingUp,
  TrendingDown,
  ArrowRight,
  RefreshCw,
  Clock
} from "lucide-react";
import * as Dialog from "@radix-ui/react-dialog";

export default function ReportsPage() {
  const [reports, setReports] = useState([
    {
      id: "oct-2023",
      title: "October 2023 Monthly Review",
      type: "MONTHLY",
      period: "Oct 1 - Oct 31, 2023",
      score: 85,
      insight: "Excellent discipline on EURUSD. Avoided overtrading during the mid-month chop.",
      createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    },
    {
      id: "wk42-2023",
      title: "Week 42 Performance",
      type: "WEEKLY",
      period: "Oct 16 - Oct 22, 2023",
      score: 62,
      insight: "Struggled with early closures. Leaving profitable trades on the table.",
      createdAt: new Date(Date.now() - 86400000 * 12).toISOString(),
    },
    {
      id: "sep-2023",
      title: "September 2023 Monthly Review",
      type: "MONTHLY",
      period: "Sep 1 - Sep 30, 2023",
      score: 92,
      insight: "Record breaking month. Solid execution on all London session setups.",
      createdAt: new Date(Date.now() - 86400000 * 35).toISOString(),
    }
  ]);

  const [generateOpen, setGenerateOpen] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);

  const handleGenerate = (e: React.FormEvent) => {
    e.preventDefault();
    setIsGenerating(true);
    // Mock generation delay
    setTimeout(() => {
      setIsGenerating(false);
      setGenerateOpen(false);
      setReports([{
        id: `new-${Date.now()}`,
        title: "Latest AI Analysis",
        type: "CUSTOM",
        period: "Last 7 Days",
        score: 78,
        insight: "Consistent execution. Need to watch out for revenge trading on Fridays.",
        createdAt: new Date().toISOString(),
      }, ...reports]);
    }, 3000);
  };

  return (
    <div className="space-y-6 max-w-6xl mx-auto">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-6 glass-card p-8 rounded-3xl border border-white/5 relative overflow-hidden">
        {/* Background Gradients */}
        <div className="absolute top-0 right-0 w-64 h-64 bg-accent opacity-10 rounded-full blur-[100px] -translate-y-1/2 translate-x-1/2" />
        <div className="absolute bottom-0 left-0 w-64 h-64 bg-success opacity-10 rounded-full blur-[100px] translate-y-1/2 -translate-x-1/2" />
        
        <div className="relative z-10 max-w-2xl">
          <h1 className="text-3xl font-bold font-heading mb-2 flex items-center gap-3">
            <Sparkles className="w-8 h-8 text-accent" />
            AI Trading Coach
          </h1>
          <p className="text-text-secondary text-base leading-relaxed">
            Get personalized insights, psychological analysis, and actionable advice generated by advanced AI trained on institutional trading patterns.
          </p>
        </div>
        
        <Dialog.Root open={generateOpen} onOpenChange={setGenerateOpen}>
          <Dialog.Trigger asChild>
            <button className="relative z-10 flex shrink-0 items-center gap-2 px-6 py-4 bg-accent hover:bg-primary-hover text-white rounded-xl text-sm font-bold shadow-lg glow-blue hover:-translate-y-0.5 transition-all text-center justify-center">
              <Bot className="w-5 h-5" />
              Generate New Report
            </button>
          </Dialog.Trigger>
          
          <Dialog.Portal>
            <Dialog.Overlay className="fixed inset-0 bg-background/80 backdrop-blur-sm z-50 animate-in fade-in" />
            <Dialog.Content className="fixed left-[50%] top-[50%] z-50 grid w-full max-w-md translate-x-[-50%] translate-y-[-50%] gap-4 glass-card border border-white/10 p-6 rounded-3xl shadow-2xl duration-200">
              <div className="flex flex-col space-y-1.5 text-center sm:text-left mb-2">
                <Dialog.Title className="text-xl font-heading font-bold flex items-center gap-2">
                  <Bot className="w-5 h-5 text-accent" /> Configure AI Report
                </Dialog.Title>
                <Dialog.Description className="text-sm text-text-secondary">
                  The AI will analyze your trades within the selected period.
                </Dialog.Description>
              </div>

              {isGenerating ? (
                <div className="py-12 flex flex-col items-center justify-center text-center">
                   <div className="relative w-20 h-20 mb-6">
                     <div className="absolute inset-0 border-4 border-white/10 rounded-full" />
                     <div className="absolute inset-0 border-4 border-accent border-r-transparent rounded-full animate-spin" />
                     <Bot className="absolute inset-0 m-auto w-8 h-8 text-accent animate-pulse" />
                   </div>
                   <h3 className="font-bold text-lg mb-2">Analyzing your trades...</h3>
                   <p className="text-sm text-text-secondary">Looking at your drawdowns, win rate, and identifying patterns in your psychology.</p>
                </div>
              ) : (
                <form onSubmit={handleGenerate} className="space-y-4">
                  <div className="space-y-2">
                    <label className="text-xs font-medium text-text-secondary">Report Period</label>
                    <select className="w-full bg-background/50 border border-white/10 rounded-xl px-4 py-3 text-sm focus:outline-none focus:ring-1 focus:ring-accent/50 focus:border-accent">
                      <option value="last7">Last 7 Days</option>
                      <option value="last30">Last 30 Days</option>
                      <option value="thisMonth">This Month</option>
                      <option value="lastMonth">Last Month</option>
                      <option value="allTime">All Time</option>
                    </select>
                  </div>
  
                  <div className="space-y-2">
                    <label className="text-xs font-medium text-text-secondary">Focus Area (Optional)</label>
                    <select className="w-full bg-background/50 border border-white/10 rounded-xl px-4 py-3 text-sm focus:outline-none focus:ring-1 focus:ring-accent/50 focus:border-accent">
                      <option value="general">General Performance</option>
                      <option value="psychology">Trading Psychology & Emotion</option>
                      <option value="risk">Risk Management & Drawdown</option>
                      <option value="strategy">Strategy Adherence</option>
                    </select>
                  </div>
  
                  <div className="pt-6 flex justify-end gap-3">
                    <button type="button" onClick={() => setGenerateOpen(false)} className="px-6 py-3 rounded-xl border border-white/10 hover:bg-white/5 text-sm font-medium transition-colors">Cancel</button>
                    <button type="submit" className="px-6 py-3 rounded-xl bg-accent hover:bg-primary-hover text-white text-sm font-medium transition-all shadow-lg glow-blue flex items-center gap-2">
                      <Sparkles className="w-4 h-4" /> Start Analysis
                    </button>
                  </div>
                </form>
              )}
            </Dialog.Content>
          </Dialog.Portal>
        </Dialog.Root>

      </div>

      <div className="flex items-center gap-2 pb-2 border-b border-white/5">
        <Clock className="w-5 h-5 text-accent" />
        <h2 className="text-lg font-bold font-heading">Previous Reports</h2>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {reports.map((report) => (
          <Link 
            key={report.id} 
            href={`/app/reports/${report.id}`}
            className="glass-card p-6 rounded-3xl border border-white/5 hover:border-white/10 hover:bg-white/5 transition-all group flex flex-col h-[280px]"
          >
            <div className="flex justify-between items-start mb-4">
              <div className="px-2.5 py-1 rounded-md text-[10px] uppercase font-bold tracking-wider bg-white/10 text-text-secondary border border-white/10 flex items-center gap-1.5">
                <CalendarDays className="w-3 h-3" /> {report.type}
              </div>
              <div className={`text-xl font-heading font-black ${
                report.score >= 80 ? 'text-success' : report.score >= 60 ? 'text-gold' : 'text-red'
              }`}>
                {report.score}/100
              </div>
            </div>

            <h3 className="font-bold text-xl leading-tight mb-2 group-hover:text-accent transition-colors line-clamp-2">
              {report.title}
            </h3>
            <p className="text-xs text-text-secondary mb-4">{report.period}</p>

            <div className="p-3 bg-background/50 rounded-xl border border-white/5 mb-4 mt-auto">
              <p className="text-sm italic text-text-secondary relative">
                <span className="text-xl text-white/10 absolute -top-2 -left-1">"</span>
                <span className="pl-3">{report.insight}</span>
              </p>
            </div>

            <div className="flex justify-between items-center text-xs text-text-secondary border-t border-white/5 pt-4">
              <span>{formatDateTime(report.createdAt).split(' ')[0]}</span>
              <span className="flex items-center gap-1 group-hover:text-white transition-colors">
                Read Full Report <ArrowRight className="w-3 h-3 group-hover:translate-x-1 transition-transform" />
              </span>
            </div>
          </Link>
        ))}
      </div>
    </div>
  );
}
